### ISSUE TITLE
Duality with compositional functions

### ISSUE THREAD

**Issue by benjamingr** [wycats/javascript-decorators#15]
It sounds to me like what this proposal does is a strict subset of what https://github.com/jhusain/compositional-functions/ does (some examples here https://github.com/jhusain/compositional-functions/issues/3 ). 

I'm wondering if it is possible to solve the issues there through giving decorators a hook to the `async` keyword using either the syntax proposed here or there and then we might be able to nail `async` decorators and the possibility of working with arbitrary async primitives and composing them in one shot.

What do you think?

**Comment by dead-claudia** [comment]
Actually, decorators work synchronously. And they can modify and/or replace method implementations pretty easily. So, no, it's not even a subset. And since the return value is assumed to be a property descriptor, you can't even `Promise` one.

**Comment by benjamingr** [comment]
Afaik compositional functions are no longer pursued anyway
