### ISSUE TITLE
wondering how to propose a feature, plan to propose  coffee style if

### ISSUE THREAD

**Issue by zzz6519003** [wycats/javascript-decorators#56]
coffee style if is so useful

```
      'active-green' if @active() and @props.currentDragItem.type == 'green'
```

:+1:

**Comment by loganfsmyth** [comment]
This would potentially conflict with the proposed decorator behavior, and would be really confusing, since you'd now have `@`-prefix syntax for two totally unrelated concepts, `decorators` and `this`. It doesn't seem like a good idea to me.

**Comment by zzz6519003** [comment]
sure, i mean the style that put if in the end,

but i just found that it can be done by isTrue ? A : B

:+1:
