### ISSUE TITLE
The new SPEC proposal is highly redundant, very limiting and does not even allow for class decoration

### ISSUE THREAD

**Issue by silkentrance** [wycats/javascript-decorators#70]
@wycats 

Given the new "SPEC" https://github.com/wycats/javascript-decorators/blob/master/interop/reusability.md

```
type Decorator = (target: Object, descriptor: DecoratorDescriptor): DecoratorDescriptor;
```

I do not see any way one would be able to decorate classes, aka constructor functions, or otherwise augment prototypes or their respective constructor functions during the decoration process?

Is this by intent or simply an oversight?

While this seems to be somewhat similar to the proposal made in #62, the latter does have support for class decorators and is not limiting in any way.

Limitations I see with the new spec proposal are
- no class decoration
- ~~~when decorating a method or property, one cannot add additional properties a/o methods to the prototype a/o constructor~~~

In addition to that I think that the new spec proposal is a bit over the top, introducing many new interfaces while a single DecoratorDescriptor interface having both a type property and a target property would suffice.

Not having the ability to decorate as freely as possible, will break existing frameworks such as Angular2 or core-decorators.js.
While the latter is not gaining the traction right now that it deserves, the former will as it is based on TypeScript, which also relies on the ability to decorate as freely as possible, including class decoration.

Please note that `having the ability to decorate as freely as possibly` does not mean that one should ignore #66, as we also need to be able to decorate generator functions.

**Comment by silkentrance** [comment]
BTW, and since Javascript is lean and mean, I think that having just one DecoratorDescriptor interface with a type property should do the trick and that one does not need any other more specialized interfaces. Otherwise, dump the type property and let users use instanceof checks instead of having it both ways.

My vote is for a single interface providing all the necessary information including the type property.

**Comment by silkentrance** [comment]
Additionally, when using a decorator, that decorator might not only want to decorate a single property or method, instead it might also want to introduce additional properties a/o methods. As such, the current new "SPEC" proposal is very limiting.

**Comment by silkentrance** [comment]
And last but not least, not having the ability to decorate as freely as possible, will break existing frameworks such as Angular2 or core-decorators.js. While the latter is not gaining the traction right now that it deserves, the former will as it is based on TypeScript, which also relies on the ability to be able to decorate as freely as possible.

**Comment by silkentrance** [comment]
And, BTW is there some platform except for ~~Twitter~~, where we could please discuss this stuff? IRC anyone? I find the current process lacking in transparency...

**Comment by dead-claudia** [comment]
@silkentrance I doubt this is intentional, but starting after the sentence/paragraph "Is this by intent or simply an oversight?", it reads a little ranty. Just trying to politely note area for improvement. :smile:

**Comment by silkentrance** [comment]
@isiahmeadows Hm, I did not mean it to sound like that, it was meant as an "objective" analysis of the current state of affairs. Will rework this as soon as I get home from work. Thanks for pointing this out.

Fixed. The description should now be "rant" free.

**Comment by silkentrance** [comment]
The new spec proposal is way more streamlined and provides for class decoration as well. Thanks @wycats and the TC39 team. Closing.
