### ISSUE TITLE
Method decorated haven't access to the property 'this' of the constructor

### ISSUE THREAD

**Issue by wzalazar** [wycats/javascript-decorators#81]
Hi, I need help with this. This is my problem...

```
@decoratorClass
export default class User {
    constructor(name) {
        this.name = name;
    }

  @decoratorMethod 
  method() {
     console.log(this.name) //is undefined, why??
  }
}
```

I don't know if is a bug or is not supported yet. Thank' s.

**Comment by loganfsmyth** [comment]
There is likely a bug in whatever `decoratorMethod` is, so more info would be needed.

**Comment by wzalazar** [comment]
Sorry, I created unit test for this case and disappeared the issue. Thanks for all.
