### ISSUE TITLE
Is the decorators proposal dead?

### ISSUE THREAD

**Issue by Download** [wycats/javascript-decorators#82]
There has been so little activity here... Or has it just moved somewhere else?

**Comment by loganfsmyth** [comment]
Not way more active necessarily, but it has moved: https://github.com/tc39/proposal-decorators

**Comment by stephenh** [comment]
Oh nice, thanks @loganfsmyth!

@wycats could you put a big "this has moved to https://github.com/tc39/proposal-decorators" at the top of this repo's readme page?

I came here via google results and spent ~30 minutes poking around before realizing this was the wrong spot. Thanks!

**Comment by RWOverdijk** [comment]
Good idea @stephenh

**Comment by viztor** [comment]
close?

**Comment by wycats** [comment]
Done!
